1.	Load the patient master CSV file into a Pandas DataFrame

📝 Note: Use pd.read_csv() and store it in a DataFrame variable.

Make sure the file path is correct.

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/pandas/patient_master_1.csv")

2.	Display the first 5 rows of the dataset

📝 Note: This helps you quickly understand column names, data format, and sample values.

In [132]:
df.head()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,Local Address,...,Normal,0.166667,-1.688900,Yes,"Navi Mumbai, Maharashtra",False,True,False,3186.0,18.4125
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,Overweight,0.600000,0.340240,Yes,"Mumbai, Maharashtra",False,True,False,1793.0,53.8275
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,Local Address,...,Normal,0.633333,0.086598,Yes,"Nashik, Maharashtra",False,False,False,2193.0,45.2000
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,Local Address,...,Normal,0.400000,-0.843425,Yes,"Mumbai, Maharashtra",False,False,False,2659.0,32.1975
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,Local Address,...,Obese,0.033333,1.439358,Yes,"Navi Mumbai, Maharashtra",False,True,False,32.0,99.0525

3.	Display the last 5 rows of the dataset

📝 Note: Useful to verify the ending records and check data completeness.

In [3]:
df.tail()

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,173,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,167,55,19.7,No,Occasionally,NaN,D105,Star Health,POL129135,2020-03-02
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

4.	Find the total number of rows and columns

📝 Note: Output should be in the form (rows, columns).

In [4]:
df.shape

(20000, 25)

5.	Display column names

📝 Note: Helps identify exact column names to avoid spelling mistakes later.

In [136]:
df.columns

Index(['Patient_ID', 'First_Name', 'Last_Name', 'Gender', 'Age',
       'Date_of_Birth', 'Blood_Group', 'Marital_Status', 'Contact_Number',
       'Address', 'City', 'State', 'Country', 'Pincode', 'Height_cm',
       'Weight_kg', 'BMI', 'Smoking_Status', 'Alcohol_Consumption',
       'Chronic_Condition', 'Primary_Doctor_ID', 'Insurance_Provider',
       'Insurance_Policy_No', 'Registration_Date', 'Registration_Date_new',
       'Under_weighted', 'Age_Group', 'Risk_level', 'Registration_Month',
       'Registartion_Year', 'Is_Senior', 'High_Risk_Patient', 'BMI_Category',
       'Height_Normalized', 'Weight_Standardized', 'Insurance_Status',
       'Patient_Location', 'high_cardiovascular_risk', 'lifestyle_counseling',
       'ICU-risk', 'BMI_Rank_In_City', 'BMI_Percentile'],
      dtype='object')

6.	Display data types of all columns

📝 Note: Verify whether numeric columns are stored as int/float and dates as object/datetime.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Patient_ID           20000 non-null  object
 1   First_Name           20000 non-null  object
 2   Last_Name            20000 non-null  object
 3   Gender               20000 non-null  object
 4   Age                  20000 non-null  int64
 5   Date_of_Birth        20000 non-null  object
 6   Blood_Group          20000 non-null  object
 7   Marital_Status       20000 non-null  object
 8   Phone_Number         20000 non-null  int64
 9   Email                20000 non-null  object
 10  Address              20000 non-null  object
 11  City                 20000 non-null  object
 12  State                20000 non-null  object
 13  Country              20000 non-null  object
 14  Pincode              20000 non-null  int64
 15  Height_cm            20000 non-null  int64
 16  Weight_kg            20000 non-null  int64
 17  BMI                  20000 non-null  float64
 18  Smoking_Status       20000 non-null  object
 19  Alcohol_Consumption  20000 non-null  object
 20  Chronic_Condition    15991 non-null  object
 21  Primary_Doctor_ID    20000 non-null  object
 22  Insurance_Provider   20000 non-null  object
 23  Insurance_Policy_No  20000 non-null  object
 24  Registration_Date    20000 non-null  object
dtypes: float64(1), int64(5), object(19)
memory usage: 3.8+ MB

In [7]:
df['Date_of_Birth'] = pd.to_datetime(df['Date_of_Birth']).dt.date

7.	Show summary statistics for numerical columns

📝 Note: Includes count, mean, min, max, and standard deviation.

In [8]:
df.describe()

,Age,Phone_Number,Pincode,Height_cm,Weight_kg,BMI
count,20000.000000,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000
mean,43.882750,9.499262e+09,405528.641150,165.002850,69.975750,25.927300
std,9.481455,2.885452e+08,3206.324183,8.910382,11.827669,5.233785
min,27.000000,9.000107e+09,400001.000000,150.000000,50.000000,15.400000
25%,36.000000,9.251704e+09,402766.500000,157.000000,60.000000,21.800000
50%,44.000000,9.497135e+09,405511.000000,165.000000,70.000000,25.600000
75%,52.000000,9.750070e+09,408298.250000,173.000000,80.000000,29.500000
max,60.000000,9.999997e+09,411099.000000,180.000000,90.000000,40.000000

8.	Show summary statistics for all columns

📝 Note: Includes categorical stats like unique values and most frequent value.

In [137]:
df.describe(include='all')

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
count,20000,20000,20000,20000,20000.000000,20000,20000,20000,2.000000e+04,20000,...,20000,20000.000000,2.000000e+04,20000,20000,20000,20000,20000,20000.000000,20000.000000
unique,20000,10,10,2,NaN,9778,8,2,NaN,1,...,4,NaN,NaN,1,5,1,2,1,NaN,NaN
top,P19984,Pooja,Patil,Male,NaN,1975-06-07,A+,Single,NaN,Local Address,...,Normal,NaN,NaN,Yes,"Pune, Maharashtra",False,True,False,NaN,NaN
freq,1,2085,2067,10142,NaN,8,2590,10027,NaN,20000,...,7809,NaN,NaN,20000,4099,20000,17667,20000,NaN,NaN
mean,NaN,NaN,NaN,NaN,43.882750,NaN,NaN,NaN,9.499262e+09,NaN,...,NaN,0.500095,-4.199308e-16,NaN,NaN,NaN,NaN,NaN,1988.926250,50.002500
std,NaN,NaN,NaN,NaN,9.481455,NaN,NaN,NaN,2.885452e+08,NaN,...,NaN,0.297013,1.000000e+00,NaN,NaN,NaN,NaN,NaN,1156.379089,28.867568
min,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,NaN,9.000107e+09,NaN,...,NaN,0.000000,-1.688900e+00,NaN,NaN,NaN,NaN,NaN,1.000000,0.030000
25%,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,NaN,9.251704e+09,NaN,...,NaN,0.233333,-8.434248e-01,NaN,NaN,NaN,NaN,NaN,990.000000,24.740000
50%,NaN,NaN,NaN,NaN,44.000000,NaN,NaN,NaN,9.497135e+09,NaN,...,NaN,0.500000,2.050277e-03,NaN,NaN,NaN,NaN,NaN,1987.000000,49.815000
75%,NaN,NaN,NaN,NaN,52.000000,NaN,NaN,NaN,9.750070e+09,NaN,...,NaN,0.766667,8.475254e-01,NaN,NaN,NaN,NaN,NaN,2992.000000,75.067500
max,NaN,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,9.999997e+09,NaN,...,NaN,1.000000,1.693001e+00,NaN,NaN,NaN,NaN,NaN,4096.000000,99.955000

9.	Check how many missing values exist per column

📝 Note: Identify columns that need data cleaning or filling.

In [139]:
df.isnull().sum()

Patient_ID                  0
First_Name                  0
Last_Name                   0
Gender                      0
Age                         0
Date_of_Birth               0
Blood_Group                 0
Marital_Status              0
Contact_Number              0
Address                     0
City                        0
State                       0
Country                     0
Pincode                     0
Height_cm                   0
Weight_kg                   0
BMI                         0
Smoking_Status              0
Alcohol_Consumption         0
Chronic_Condition           0
Primary_Doctor_ID           0
Insurance_Provider          0
Insurance_Policy_No         0
Registration_Date           0
Registration_Date_new       0
Under_weighted              0
Age_Group                   0
Risk_level                  0
Registration_Month          0
Registartion_Year           0
Is_Senior                   0
High_Risk_Patient           0
BMI_Category                0
Height_Normalized           0
Weight_Standardized         0
Insurance_Status            0
Patient_Location            0
high_cardiovascular_risk    0
lifestyle_counseling        0
ICU-risk                    0
BMI_Rank_In_City            0
BMI_Percentile              0
dtype: int64

10.	Check if the dataset contains duplicate Patient_IDs

📝 Note: Patient_ID should be unique; duplicates indicate data quality issues.

In [140]:
df['Patient_ID'].duplicated().sum()

np.int64(0)

11.	Find the total number of unique patients

📝 Note: Use Patient_ID to verify uniqueness.

In [141]:
df['Patient_ID'].nunique()

20000

12.	Display memory usage of the DataFrame

📝 Note: Important when working with large healthcare datasets.

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Patient_ID                20000 non-null  object
 1   First_Name                20000 non-null  object
 2   Last_Name                 20000 non-null  object
 3   Gender                    20000 non-null  category
 4   Age                       20000 non-null  int64
 5   Date_of_Birth             20000 non-null  object
 6   Blood_Group               20000 non-null  category
 7   Marital_Status            20000 non-null  object
 8   Contact_Number            20000 non-null  int64
 9   Address                   20000 non-null  object
 10  City                      20000 non-null  object
 11  State                     20000 non-null  object
 12  Country                   20000 non-null  object
 13  Pincode                   20000 non-null  int64
 14  Height_cm                 20000 non-null  int64
 15  Weight_kg                 20000 non-null  int64
 16  BMI                       20000 non-null  float64
 17  Smoking_Status            20000 non-null  object
 18  Alcohol_Consumption       20000 non-null  object
 19  Chronic_Condition         20000 non-null  object
 20  Primary_Doctor_ID         20000 non-null  object
 21  Insurance_Provider        20000 non-null  object
 22  Insurance_Policy_No       20000 non-null  object
 23  Registration_Date         20000 non-null  object
 24  Registration_Date_new     20000 non-null  int32
 25  Under_weighted            20000 non-null  bool
 26  Age_Group                 20000 non-null  object
 27  Risk_level                20000 non-null  object
 28  Registration_Month        20000 non-null  int32
 29  Registartion_Year         20000 non-null  int32
 30  Is_Senior                 20000 non-null  object
 31  High_Risk_Patient         20000 non-null  bool
 32  BMI_Category              20000 non-null  object
 33  Height_Normalized         20000 non-null  float64
 34  Weight_Standardized       20000 non-null  float64
 35  Insurance_Status          20000 non-null  object
 36  Patient_Location          20000 non-null  object
 37  high_cardiovascular_risk  20000 non-null  bool
 38  lifestyle_counseling      20000 non-null  bool
 39  ICU-risk                  20000 non-null  bool
 40  BMI_Rank_In_City          20000 non-null  float64
 41  BMI_Percentile            20000 non-null  float64
dtypes: bool(5), category(2), float64(5), int32(3), int64(5), object(22)
memory usage: 5.2+ MB

13.	Sort patients by Age in descending order

📝 Note: Oldest patients should appear first.

In [143]:
df.sort_values(by='Age', ascending=False)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
8399,P08400,Sneha,Singh,Female,60,1965-08-07,AB-,Single,9095205309,Local Address,...,Normal,0.333333,-0.589782,Yes,"Mumbai, Maharashtra",False,False,False,2217.0,43.1875
19,P00020,Pooja,Joshi,Female,60,1965-07-26,B+,Single,9602891328,Local Address,...,Obese,0.733333,1.608453,Yes,"Pune, Maharashtra",False,True,False,864.0,78.2425
14971,P14972,Sneha,Sharma,Female,60,1965-04-13,A-,Single,9763313339,Local Address,...,Normal,0.833333,-0.505235,Yes,"Nagpur, Maharashtra",False,True,False,3218.0,18.9575
1148,P01149,Anjali,Verma,Male,60,1965-04-25,O+,Single,9311576340,Local Address,...,Overweight,0.166667,-0.420687,Yes,"Mumbai, Maharashtra",False,True,False,1562.0,59.8925
1149,P01150,Neha,Gupta,Male,60,1965-04-25,A+,Married,9481744526,Local Address,...,Obese,0.533333,1.270263,Yes,"Navi Mumbai, Maharashtra",False,True,False,706.0,81.1975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13482,P13483,Anjali,Singh,Female,27,1998-01-11,A+,Single,9282284476,Local Address,...,Overweight,0.366667,0.424788,Yes,"Mumbai, Maharashtra",False,True,False,1131.0,71.2025
8050,P08051,Rahul,Patil,Female,27,1998-01-10,B-,Single,9492374105,Local Address,...,Underweight,0.900000,-1.350710,Yes,"Pune, Maharashtra",False,False,False,3968.0,2.5175
16179,P16180,Anjali,Patil,Male,27,1998-01-18,A+,Married,9690272656,Local Address,...,Overweight,0.400000,0.171145,Yes,"Navi Mumbai, Maharashtra",False,True,False,1486.0,61.9425
16191,P16192,Anjali,Gupta,Male,27,1998-01-18,AB-,Single,9619731561,Local Address,...,Obese,0.300000,0.932073,Yes,"Navi Mumbai, Maharashtra",False,True,False,500.0,86.0650
3456,P03457,Vikas,Verma,Female,27,1998-01-16,A+,Married,9443674753,Local Address,...,Normal,0.800000,0.424788,Yes,"Pune, Maharashtra",False,True,False,2294.0,44.5775

14.	Sort patients by Registration_Date in ascending order

📝 Note: Earliest registered patients should appear first.

In [144]:
df.sort_values(by='Registration_Date', ascending=True)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
17264,P17265,Amit,Iyer,Male,46,1979-12-10,O+,Single,9104218759,Local Address,...,Overweight,0.300000,-0.082497,Yes,"Navi Mumbai, Maharashtra",False,True,False,1514.0,61.2675
16781,P16782,Amit,Gupta,Male,35,1990-07-15,A-,Married,9030455935,Local Address,...,Normal,0.833333,-0.082497,Yes,"Nagpur, Maharashtra",False,True,False,2816.0,29.4375
3817,P03818,Vikas,Kulkarni,Male,37,1988-10-20,O+,Single,9196624830,Local Address,...,Obese,0.033333,0.171145,Yes,"Nagpur, Maharashtra",False,True,False,615.0,84.5575
3955,P03956,Rohan,Mehta,Female,44,1981-03-03,AB-,Married,9639101257,Local Address,...,Overweight,0.333333,0.340240,Yes,"Nashik, Maharashtra",False,True,False,1139.0,71.2025
18676,P18677,Rohan,Mehta,Female,34,1991-11-30,B+,Married,9720232207,Local Address,...,Obese,0.000000,0.255693,Yes,"Pune, Maharashtra",False,True,False,521.0,87.2875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9220,P09221,Anjali,Sharma,Male,40,1985-07-24,B+,Married,9565398228,Local Address,...,Obese,0.266667,0.509335,Yes,"Navi Mumbai, Maharashtra",False,True,False,787.0,79.4525
934,P00935,Suresh,Gupta,Female,52,1973-01-17,O-,Married,9536300592,Local Address,...,Obese,0.666667,1.439358,Yes,"Mumbai, Maharashtra",False,True,False,840.0,78.2425
4328,P04329,Kavita,Mehta,Female,47,1978-07-01,A+,Married,9318381480,Local Address,...,Normal,0.766667,-1.097067,Yes,"Pune, Maharashtra",False,True,False,3718.0,9.0525
1431,P01432,Amit,Kulkarni,Female,35,1990-11-21,A-,Married,9783573955,Local Address,...,Overweight,0.600000,1.016620,Yes,"Navi Mumbai, Maharashtra",False,True,False,1077.0,72.5650
11977,P11978,Rahul,Iyer,Male,55,1970-06-03,AB-,Single,9384205947,Local Address,...,Obese,0.400000,1.101168,Yes,"Nashik, Maharashtra",False,True,False,588.0,84.5575

15.	Display random 10 patient records

📝 Note: Random sampling helps quick data inspection

In [16]:
df.sample(10)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
6800,P06801,Rohan,Singh,Male,41,1984-05-30,A+,Single,9915181511,user6801@mail.com,...,150,51,22.7,No,Occasionally,Hypertension,D102,HDFC Ergo,POL843196,2020-06-23
6452,P06453,Amit,Mehta,Female,57,1968-11-03,AB+,Single,9743915141,user6453@mail.com,...,173,50,16.7,No,Occasionally,NaN,D103,New India Assurance,POL811446,2020-03-26
18912,P18913,Vikas,Joshi,Female,60,1965-09-06,A+,Married,9075855347,user18913@mail.com,...,164,83,30.9,No,Occasionally,Thyroid,D103,ICICI Lombard,POL325408,2023-03-13
18309,P18310,Rohan,Joshi,Male,43,1982-07-12,O-,Married,9275297219,user18310@mail.com,...,162,58,22.1,No,Occasionally,Thyroid,D108,New India Assurance,POL966853,2021-07-13
5525,P05526,Amit,Sharma,Male,44,1981-07-11,O-,Married,9562176283,user5526@mail.com,...,180,84,25.9,Yes,Occasionally,Hypertension,D108,Star Health,POL753291,2020-09-26
4917,P04918,Amit,Joshi,Male,35,1990-05-10,B-,Married,9355121143,user4918@mail.com,...,155,58,24.1,No,No,NaN,D103,HDFC Ergo,POL529513,2022-02-09
13496,P13497,Suresh,Nair,Male,35,1990-05-31,AB-,Single,9180534560,user13497@mail.com,...,157,86,34.9,Yes,Occasionally,Thyroid,D100,New India Assurance,POL818155,2021-06-03
12363,P12364,Amit,Nair,Female,29,1996-06-01,AB+,Single,9917187755,user12364@mail.com,...,177,79,25.2,Yes,Occasionally,Asthma,D102,Reliance General,POL884423,2023-06-07
19175,P19176,Suresh,Joshi,Female,39,1986-06-12,O-,Married,9146439135,user19176@mail.com,...,179,77,24.0,Yes,Occasionally,Thyroid,D101,Reliance General,POL507000,2020-05-06
18752,P18753,Rahul,Patil,Female,37,1988-10-18,AB+,Married,9840069890,user18753@mail.com,...,168,76,26.9,Yes,Occasionally,NaN,D109,New India Assurance,POL675204,2023-11-19

**🔹 SECTION 2: FILTERING & CONDITIONAL SELECTION (16–35)**

16.	Find all male patients

📝 Note: Filter rows where Gender equals "Male".

In [145]:
df[df['Gender']=='Male']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,Local Address,...,Normal,0.166667,-1.688900,Yes,"Navi Mumbai, Maharashtra",False,True,False,3186.0,18.4125
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,Local Address,...,Normal,0.633333,0.086598,Yes,"Nashik, Maharashtra",False,False,False,2193.0,45.2000
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,Local Address,...,Normal,0.400000,-0.843425,Yes,"Mumbai, Maharashtra",False,False,False,2659.0,32.1975
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,Local Address,...,Obese,0.033333,1.439358,Yes,"Navi Mumbai, Maharashtra",False,True,False,32.0,99.0525
5,P00006,Suresh,Kulkarni,Male,46,1979-09-03,A+,Married,9469747118,Local Address,...,Obese,0.400000,1.270263,Yes,"Navi Mumbai, Maharashtra",False,True,False,468.0,87.2875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19988,P19989,Vikas,Patil,Male,54,1971-07-25,AB-,Married,9087089590,Local Address,...,Normal,0.233333,-0.927972,Yes,"Pune, Maharashtra",False,True,False,2520.0,38.6975
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,Local Address,...,Underweight,0.933333,-1.266162,Yes,"Mumbai, Maharashtra",False,True,False,3822.0,2.9900
19990,P19991,Vikas,Joshi,Male,55,1970-05-20,O+,Single,9551275487,Local Address,...,Overweight,0.333333,0.002050,Yes,"Nagpur, Maharashtra",False,True,False,1532.0,61.2675
19994,P19995,Suresh,Singh,Male,58,1967-01-14,AB+,Married,9142595611,Local Address,...,Obese,0.200000,0.593883,Yes,"Navi Mumbai, Maharashtra",False,True,False,557.0,84.5575
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,Local Address,...,Normal,0.766667,-0.589782,Yes,"Navi Mumbai, Maharashtra",False,True,False,3128.0,19.5950

17.	Find all female patients above 50 years

📝 Note: Apply two conditions: Gender = Female AND Age > 50.

In [18]:
df[(df['Gender']=='Female') & (df['Age']>=50)]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,user8@mail.com,...,173,60,20.0,Yes,Occasionally,Hypertension,D100,HDFC Ergo,POL523880,2022-03-23
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,user11@mail.com,...,180,89,27.5,Yes,No,Hypertension,D104,Reliance General,POL777223,2021-04-24
11,P00012,Rahul,Mehta,Female,50,1975-11-26,AB-,Married,9380410557,user12@mail.com,...,170,82,28.4,No,Occasionally,Asthma,D110,Reliance General,POL684731,2022-12-15
12,P00013,Vikas,Verma,Female,56,1969-08-17,A-,Single,9895288162,user13@mail.com,...,165,86,31.6,No,No,NaN,D102,Reliance General,POL970598,2022-10-01
18,P00019,Rahul,Iyer,Female,50,1975-05-13,O-,Single,9270700539,user19@mail.com,...,167,85,30.5,No,Occasionally,Thyroid,D109,New India Assurance,POL826506,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19968,P19969,Suresh,Singh,Female,56,1969-09-07,AB-,Married,9880393201,user19969@mail.com,...,170,65,22.5,No,Occasionally,NaN,D102,Star Health,POL690634,2020-03-29
19983,P19984,Rahul,Iyer,Female,54,1971-07-06,A+,Married,9242052517,user19984@mail.com,...,174,55,18.2,Yes,No,Diabetes,D102,New India Assurance,POL778154,2021-12-26
19992,P19993,Rahul,Iyer,Female,58,1967-01-17,AB-,Single,9138504573,user19993@mail.com,...,174,63,20.8,No,No,Diabetes,D104,Star Health,POL871461,2020-12-23
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

18.	Find patients from Pune city

📝 Note: Match exact city name in City column.

In [19]:
df[df['City'] == 'Pune']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,user7@mail.com,...,176,88,28.4,Yes,No,NaN,D108,Reliance General,POL682287,2020-03-22
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,user8@mail.com,...,173,60,20.0,Yes,Occasionally,Hypertension,D100,HDFC Ergo,POL523880,2022-03-23
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,user11@mail.com,...,180,89,27.5,Yes,No,Hypertension,D104,Reliance General,POL777223,2021-04-24
15,P00016,Pooja,Iyer,Male,41,1984-04-04,AB-,Married,9131640457,user16@mail.com,...,152,86,37.2,Yes,Occasionally,Diabetes,D107,Reliance General,POL773678,2022-10-31
16,P00017,Neha,Gupta,Female,37,1988-05-03,B-,Single,9625970283,user17@mail.com,...,177,52,16.6,Yes,Occasionally,NaN,D107,HDFC Ergo,POL948459,2020-07-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19966,P19967,Kavita,Patil,Female,57,1968-12-21,A-,Single,9771991467,user19967@mail.com,...,173,89,29.7,Yes,No,Hypertension,D107,Reliance General,POL374313,2022-07-11
19970,P19971,Vikas,Singh,Male,50,1975-08-05,B-,Single,9694795979,user19971@mail.com,...,154,80,33.7,No,Occasionally,Hypertension,D100,Reliance General,POL958429,2022-09-12
19972,P19973,Neha,Kulkarni,Male,54,1971-02-04,B-,Married,9719340286,user19973@mail.com,...,166,53,19.2,No,No,Hypertension,D110,Reliance General,POL544991,2023-02-27
19987,P19988,Rohan,Joshi,Male,46,1979-05-02,B-,Married,9549739409,user19988@mail.com,...,163,59,22.2,No,No,NaN,D105,HDFC Ergo,POL189197,2023-08-05
19988,P19989,Vikas,Patil,Male,54,1971-07-25,AB-,Married,9087089590,user19989@mail.com,...,157,59,23.9,No,Occasionally,Hypertension,D103,ICICI Lombard,POL272280,2023-10-27

19.	Find patients suffering from Diabetes

📝 Note: Use Chronic_Condition column and filter "Diabetes".

In [20]:
df[df['Chronic_Condition']=='Diabetes']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,162,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17
13,P00014,Suresh,Mehta,Female,39,1986-05-10,A-,Married,9240144188,user14@mail.com,...,165,76,27.9,Yes,No,Diabetes,D102,Star Health,POL980183,2022-12-17
15,P00016,Pooja,Iyer,Male,41,1984-04-04,AB-,Married,9131640457,user16@mail.com,...,152,86,37.2,Yes,Occasionally,Diabetes,D107,Reliance General,POL773678,2022-10-31
19,P00020,Pooja,Joshi,Female,60,1965-07-26,B+,Single,9602891328,user20@mail.com,...,172,89,30.1,Yes,No,Diabetes,D109,New India Assurance,POL316461,2022-04-16
24,P00025,Pooja,Nair,Male,34,1991-01-25,AB+,Single,9415300588,user25@mail.com,...,163,58,21.8,Yes,Occasionally,Diabetes,D103,New India Assurance,POL974247,2021-12-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19982,P19983,Rohan,Mehta,Male,42,1983-04-13,B+,Single,9143638855,user19983@mail.com,...,175,86,28.1,No,Occasionally,Diabetes,D100,New India Assurance,POL483547,2023-03-18
19983,P19984,Rahul,Iyer,Female,54,1971-07-06,A+,Married,9242052517,user19984@mail.com,...,174,55,18.2,Yes,No,Diabetes,D102,New India Assurance,POL778154,2021-12-26
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,178,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08
19992,P19993,Rahul,Iyer,Female,58,1967-01-17,AB-,Single,9138504573,user19993@mail.com,...,174,63,20.8,No,No,Diabetes,D104,Star Health,POL871461,2020-12-23
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,173,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05

20.	Find patients who are smokers

📝 Note: Filter Smoking_Status column for "Yes".

In [21]:
df[df['Smoking_Status']=='Yes']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,168,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,user7@mail.com,...,176,88,28.4,Yes,No,NaN,D108,Reliance General,POL682287,2020-03-22
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,user8@mail.com,...,173,60,20.0,Yes,Occasionally,Hypertension,D100,HDFC Ergo,POL523880,2022-03-23
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,user9@mail.com,...,155,68,28.3,Yes,No,Asthma,D103,Star Health,POL233712,2020-10-24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19994,P19995,Suresh,Singh,Male,58,1967-01-14,AB+,Married,9142595611,user19995@mail.com,...,156,77,31.6,Yes,No,Hypertension,D109,HDFC Ergo,POL281542,2021-12-02
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

21.	Find patients who consume alcohol occasionally

📝 Note: Match Alcohol_Consumption = "Occasionally".

In [146]:
df[df['Alcohol_Consumption']=='Occasionally']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,Local Address,...,Normal,0.166667,-1.688900,Yes,"Navi Mumbai, Maharashtra",False,True,False,3186.0,18.4125
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,Overweight,0.600000,0.340240,Yes,"Mumbai, Maharashtra",False,True,False,1793.0,53.8275
5,P00006,Suresh,Kulkarni,Male,46,1979-09-03,A+,Married,9469747118,Local Address,...,Obese,0.400000,1.270263,Yes,"Navi Mumbai, Maharashtra",False,True,False,468.0,87.2875
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,Local Address,...,Normal,0.766667,-0.843425,Yes,"Pune, Maharashtra",False,True,False,3511.0,13.9500
9,P00010,Vikas,Nair,Male,58,1967-11-03,AB+,Married,9471311790,Local Address,...,Normal,0.500000,-0.251592,Yes,"Nagpur, Maharashtra",False,True,False,2251.0,43.1875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,Local Address,...,Normal,0.766667,-0.589782,Yes,"Navi Mumbai, Maharashtra",False,True,False,3128.0,19.5950
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,Local Address,...,Normal,0.800000,-0.758877,Yes,"Navi Mumbai, Maharashtra",False,True,False,3328.0,14.4375
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,Local Address,...,Normal,0.566667,-1.266162,Yes,"Nagpur, Maharashtra",False,True,False,3520.0,12.3325
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,Local Address,...,Overweight,0.233333,0.086598,Yes,"Nagpur, Maharashtra",False,True,False,1145.0,70.8675
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,Local Address,...,Obese,0.166667,1.608453,Yes,"Nagpur, Maharashtra",False,True,False,90.0,97.7850

22.	Find patients with BMI greater than 30

📝 Note: BMI > 30 is considered obese (high risk).

In [23]:
df[df['BMI']>30]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,151,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04
5,P00006,Suresh,Kulkarni,Male,46,1979-09-03,A+,Married,9469747118,user6@mail.com,...,162,85,32.4,No,Occasionally,NaN,D110,ICICI Lombard,POL589437,2022-01-24
12,P00013,Vikas,Verma,Female,56,1969-08-17,A-,Single,9895288162,user13@mail.com,...,165,86,31.6,No,No,NaN,D102,Reliance General,POL970598,2022-10-01
15,P00016,Pooja,Iyer,Male,41,1984-04-04,AB-,Married,9131640457,user16@mail.com,...,152,86,37.2,Yes,Occasionally,Diabetes,D107,Reliance General,POL773678,2022-10-31
18,P00019,Rahul,Iyer,Female,50,1975-05-13,O-,Single,9270700539,user19@mail.com,...,167,85,30.5,No,Occasionally,Thyroid,D109,New India Assurance,POL826506,2024-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19975,P19976,Amit,Gupta,Male,57,1968-04-20,AB-,Married,9460741360,user19976@mail.com,...,153,76,32.5,No,Occasionally,NaN,D106,New India Assurance,POL620514,2023-06-17
19977,P19978,Rahul,Gupta,Male,43,1982-07-27,AB-,Married,9402505693,user19978@mail.com,...,159,79,31.2,Yes,Occasionally,Diabetes,D104,HDFC Ergo,POL462578,2022-11-21
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19994,P19995,Suresh,Singh,Male,58,1967-01-14,AB+,Married,9142595611,user19995@mail.com,...,156,77,31.6,Yes,No,Hypertension,D109,HDFC Ergo,POL281542,2021-12-02
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

23.	Find patients with no chronic condition

📝 Note: Chronic_Condition value should be "None".

In [147]:
df[df['Chronic_Condition']=='None']

Empty DataFrame
Columns: [Patient_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, Blood_Group, Marital_Status, Contact_Number, Address, City, State, Country, Pincode, Height_cm, Weight_kg, BMI, Smoking_Status, Alcohol_Consumption, Chronic_Condition, Primary_Doctor_ID, Insurance_Provider, Insurance_Policy_No, Registration_Date, Registration_Date_new, Under_weighted, Age_Group, Risk_level, Registration_Month, Registartion_Year, Is_Senior, High_Risk_Patient, BMI_Category, Height_Normalized, Weight_Standardized, Insurance_Status, Patient_Location, high_cardiovascular_risk, lifestyle_counseling, ICU-risk, BMI_Rank_In_City, BMI_Percentile]
Index: []

[0 rows x 42 columns]

24.	Find patients registered after 2023

📝 Note: Convert Registration_Date to datetime and compare year > 2023.

In [25]:
df['Registration_Date_new']=pd.to_datetime(df['Registration_Date'])

In [26]:
df['Registration_Date_new']=df['Registration_Date_new'].dt.year

In [27]:
df[df['Registration_Date_new']==2023]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19,2023
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12,2023
14,P00015,Suresh,Gupta,Male,50,1975-10-23,B-,Single,9498079887,user15@mail.com,...,75,25.6,No,No,Thyroid,D106,HDFC Ergo,POL258655,2023-10-12,2023
22,P00023,Pooja,Mehta,Male,56,1969-12-16,AB+,Married,9503854398,user23@mail.com,...,69,21.5,No,Occasionally,Hypertension,D108,Star Health,POL979936,2023-02-13,2023
26,P00027,Amit,Patil,Male,35,1990-05-07,AB-,Married,9939874149,user27@mail.com,...,57,18.0,No,Occasionally,Asthma,D108,Star Health,POL849460,2023-09-01,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19982,P19983,Rohan,Mehta,Male,42,1983-04-13,B+,Single,9143638855,user19983@mail.com,...,86,28.1,No,Occasionally,Diabetes,D100,New India Assurance,POL483547,2023-03-18,2023
19987,P19988,Rohan,Joshi,Male,46,1979-05-02,B-,Married,9549739409,user19988@mail.com,...,59,22.2,No,No,NaN,D105,HDFC Ergo,POL189197,2023-08-05,2023
19988,P19989,Vikas,Patil,Male,54,1971-07-25,AB-,Married,9087089590,user19989@mail.com,...,59,23.9,No,Occasionally,Hypertension,D103,ICICI Lombard,POL272280,2023-10-27,2023
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03,2023
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02,2023

25.	Find patients with blood group O+

📝 Note: Exact string match "O+".

In [148]:
df[df['Blood_Group']=='O+']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
20,P00021,Neha,Patil,Female,33,1992-01-08,O+,Single,9560697611,Local Address,...,Normal,1.000000,-0.674330,Yes,"Mumbai, Maharashtra",False,True,False,3575.0,9.4350
23,P00024,Rahul,Patil,Male,31,1994-08-24,O+,Married,9920694229,Local Address,...,Overweight,0.300000,-0.420687,Yes,"Pune, Maharashtra",False,True,False,2053.0,50.4325
35,P00036,Anjali,Patil,Male,54,1971-02-24,O+,Single,9622342097,Local Address,...,Normal,0.666667,-0.251592,Yes,"Nashik, Maharashtra",False,False,False,2638.0,34.2250
37,P00038,Suresh,Nair,Female,39,1986-02-03,O+,Single,9992549306,Local Address,...,Overweight,0.000000,-1.012520,Yes,"Mumbai, Maharashtra",False,True,False,1900.0,51.0450
45,P00046,Vikas,Joshi,Male,55,1970-10-11,O+,Married,9078313448,Local Address,...,Overweight,0.233333,-0.674330,Yes,"Pune, Maharashtra",False,True,False,2171.0,47.2850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19976,P19977,Amit,Singh,Female,39,1986-05-18,O+,Single,9499414364,Local Address,...,Overweight,0.300000,0.086598,Yes,"Nagpur, Maharashtra",False,True,False,1333.0,66.4275
19978,P19979,Kavita,Gupta,Male,42,1983-09-27,O+,Married,9514834444,Local Address,...,Normal,0.433333,-0.505235,Yes,"Nagpur, Maharashtra",False,True,False,2382.0,40.0675
19979,P19980,Amit,Gupta,Female,43,1982-08-17,O+,Single,9312722710,Local Address,...,Overweight,0.366667,-0.420687,Yes,"Nashik, Maharashtra",False,True,False,2136.0,46.5925
19981,P19982,Vikas,Singh,Female,42,1983-10-27,O+,Single,9179699811,Local Address,...,Normal,0.466667,-0.758877,Yes,"Navi Mumbai, Maharashtra",False,False,False,2692.0,30.6725
19990,P19991,Vikas,Joshi,Male,55,1970-05-20,O+,Single,9551275487,Local Address,...,Overweight,0.333333,0.002050,Yes,"Nagpur, Maharashtra",False,True,False,1532.0,61.2675

26.	Find patients insured under Star Health

📝 Note: Filter Insurance_Provider column.

In [149]:
df[df['Insurance_Provider']=='Star Health']

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,Overweight,0.600000,0.340240,Yes,"Mumbai, Maharashtra",False,True,False,1793.0,53.8275
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,Local Address,...,Overweight,0.166667,-0.167045,Yes,"Navi Mumbai, Maharashtra",False,True,False,1277.0,67.4250
13,P00014,Suresh,Mehta,Female,39,1986-05-10,A-,Married,9240144188,Local Address,...,Overweight,0.500000,0.509335,Yes,"Navi Mumbai, Maharashtra",False,True,False,1357.0,65.2025
22,P00023,Pooja,Mehta,Male,56,1969-12-16,AB+,Married,9503854398,Local Address,...,Normal,0.966667,-0.082497,Yes,"Pune, Maharashtra",False,True,False,3164.0,22.7700
26,P00027,Amit,Patil,Male,35,1990-05-07,AB-,Married,9939874149,Local Address,...,Underweight,0.933333,-1.097067,Yes,"Mumbai, Maharashtra",False,True,False,3752.0,4.8875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19969,P19970,Kavita,Kulkarni,Male,39,1986-09-11,A+,Married,9778593560,Local Address,...,Normal,0.200000,-1.519805,Yes,"Nashik, Maharashtra",False,True,False,3137.0,22.0825
19980,P19981,Kavita,Singh,Female,40,1985-01-07,B-,Married,9467940100,Local Address,...,Overweight,0.433333,0.340240,Yes,"Nashik, Maharashtra",False,True,False,1380.0,65.2025
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,Local Address,...,Underweight,0.933333,-1.266162,Yes,"Mumbai, Maharashtra",False,True,False,3822.0,2.9900
19992,P19993,Rahul,Iyer,Female,58,1967-01-17,AB-,Single,9138504573,Local Address,...,Normal,0.800000,-0.589782,Yes,"Navi Mumbai, Maharashtra",False,False,False,3186.0,18.4125
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,Local Address,...,Normal,0.566667,-1.266162,Yes,"Nagpur, Maharashtra",False,True,False,3520.0,12.3325

27.	Find patients whose height is above 175 cm

📝 Note: Numeric filtering using Height_cm column.

In [150]:
df[df['Height_cm']>175]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,Local Address,...,Overweight,0.866667,1.523905,Yes,"Pune, Maharashtra",False,True,False,1296.0,68.3025
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,Local Address,...,Overweight,1.000000,1.608453,Yes,"Pune, Maharashtra",False,True,False,1537.0,62.6025
16,P00017,Neha,Gupta,Female,37,1988-05-03,B-,Single,9625970283,Local Address,...,Underweight,0.900000,-1.519805,Yes,"Pune, Maharashtra",False,True,False,4029.0,1.2525
20,P00021,Neha,Patil,Female,33,1992-01-08,O+,Single,9560697611,Local Address,...,Normal,1.000000,-0.674330,Yes,"Mumbai, Maharashtra",False,True,False,3575.0,9.4350
22,P00023,Pooja,Mehta,Male,56,1969-12-16,AB+,Married,9503854398,Local Address,...,Normal,0.966667,-0.082497,Yes,"Pune, Maharashtra",False,True,False,3164.0,22.7700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19953,P19954,Sneha,Iyer,Male,55,1970-10-26,A-,Married,9207604119,Local Address,...,Normal,0.900000,0.002050,Yes,"Nashik, Maharashtra",False,True,False,2886.0,28.2650
19959,P19960,Pooja,Mehta,Female,53,1972-05-08,O-,Single,9104002737,Local Address,...,Normal,1.000000,0.255693,Yes,"Navi Mumbai, Maharashtra",False,True,False,2734.0,29.4375
19984,P19985,Amit,Mehta,Female,30,1995-03-25,O-,Single,9569006453,Local Address,...,Underweight,0.933333,-1.181615,Yes,"Nagpur, Maharashtra",False,True,False,3882.0,3.8575
19985,P19986,Anjali,Mehta,Male,46,1979-05-15,AB+,Single,9010102699,Local Address,...,Normal,0.866667,-0.420687,Yes,"Navi Mumbai, Maharashtra",False,True,False,3128.0,19.5950
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,Local Address,...,Underweight,0.933333,-1.266162,Yes,"Mumbai, Maharashtra",False,True,False,3822.0,2.9900

28.	Find patients aged between 30 and 45

📝 Note: Age >= 30 AND Age <= 45.

In [31]:
df[(df['Age']>=30) & (df['Age']<=45)]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19,2023
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12,2023
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04,2021
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,user7@mail.com,...,88,28.4,Yes,No,NaN,D108,Reliance General,POL682287,2020-03-22,2020
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,user9@mail.com,...,68,28.3,Yes,No,Asthma,D103,Star Health,POL233712,2020-10-24,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08,2022
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03,2023
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05,2020
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03,2021
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02,2023

29.	Find patients from Mumbai OR Pune

📝 Note: Use OR condition or isin().

In [151]:
df[(df['City'] == 'Mumbai') | (df['City'] == 'Pune')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location,high_cardiovascular_risk,lifestyle_counseling,ICU-risk,BMI_Rank_In_City,BMI_Percentile
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,Overweight,0.600000,0.340240,Yes,"Mumbai, Maharashtra",False,True,False,1793.0,53.8275
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,Local Address,...,Normal,0.400000,-0.843425,Yes,"Mumbai, Maharashtra",False,False,False,2659.0,32.1975
6,P00007,Suresh,Nair,Male,42,1983-02-17,B-,Single,9199546251,Local Address,...,Overweight,0.866667,1.523905,Yes,"Pune, Maharashtra",False,True,False,1296.0,68.3025
7,P00008,Vikas,Gupta,Female,59,1966-03-23,AB+,Married,9000565982,Local Address,...,Normal,0.766667,-0.843425,Yes,"Pune, Maharashtra",False,True,False,3511.0,13.9500
10,P00011,Sneha,Verma,Female,51,1974-03-31,O-,Single,9227251578,Local Address,...,Overweight,1.000000,1.608453,Yes,"Pune, Maharashtra",False,True,False,1537.0,62.6025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19987,P19988,Rohan,Joshi,Male,46,1979-05-02,B-,Married,9549739409,Local Address,...,Normal,0.433333,-0.927972,Yes,"Pune, Maharashtra",False,False,False,2965.0,27.6075
19988,P19989,Vikas,Patil,Male,54,1971-07-25,AB-,Married,9087089590,Local Address,...,Normal,0.233333,-0.927972,Yes,"Pune, Maharashtra",False,True,False,2520.0,38.6975
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,Local Address,...,Underweight,0.933333,-1.266162,Yes,"Mumbai, Maharashtra",False,True,False,3822.0,2.9900
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,Local Address,...,Obese,0.300000,1.270263,Yes,"Mumbai, Maharashtra",False,True,False,341.0,90.9850
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,Local Address,...,Normal,0.766667,-0.674330,Yes,"Mumbai, Maharashtra",False,True,False,3234.0,17.7775

30.	Find patients who are married and diabetic

📝 Note: Marital_Status = Married AND Chronic_Condition = Diabetes.

In [33]:
df[(df['Marital_Status']=='Married') & (df['Chronic_Condition'] == 'Diabetes')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17,2020
13,P00014,Suresh,Mehta,Female,39,1986-05-10,A-,Married,9240144188,user14@mail.com,...,76,27.9,Yes,No,Diabetes,D102,Star Health,POL980183,2022-12-17,2022
15,P00016,Pooja,Iyer,Male,41,1984-04-04,AB-,Married,9131640457,user16@mail.com,...,86,37.2,Yes,Occasionally,Diabetes,D107,Reliance General,POL773678,2022-10-31,2022
30,P00031,Vikas,Patil,Male,46,1979-10-08,O-,Married,9558075342,user31@mail.com,...,51,21.5,No,Occasionally,Diabetes,D109,Star Health,POL496551,2020-02-26,2020
34,P00035,Amit,Nair,Male,46,1979-02-01,O-,Married,9924224974,user35@mail.com,...,78,25.8,No,Occasionally,Diabetes,D109,Star Health,POL338388,2023-10-26,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19953,P19954,Sneha,Iyer,Male,55,1970-10-26,A-,Married,9207604119,user19954@mail.com,...,70,22.3,Yes,No,Diabetes,D107,Reliance General,POL230841,2022-06-22,2022
19977,P19978,Rahul,Gupta,Male,43,1982-07-27,AB-,Married,9402505693,user19978@mail.com,...,79,31.2,Yes,Occasionally,Diabetes,D104,HDFC Ergo,POL462578,2022-11-21,2022
19983,P19984,Rahul,Iyer,Female,54,1971-07-06,A+,Married,9242052517,user19984@mail.com,...,55,18.2,Yes,No,Diabetes,D102,New India Assurance,POL778154,2021-12-26,2021
19989,P19990,Pooja,Joshi,Male,35,1990-07-24,AB-,Married,9823010533,user19990@mail.com,...,55,17.4,Yes,Occasionally,Diabetes,D108,Star Health,POL229492,2022-07-08,2022
19993,P19994,Anjali,Joshi,Female,43,1982-04-25,O-,Married,9864695122,user19994@mail.com,...,62,20.7,No,Occasionally,Diabetes,D109,Reliance General,POL507705,2020-07-05,2020

31.	Find patients whose email contains “gmail”

📝 Note: Use string methods for partial match.

In [158]:
df[df['Email'].str.contains('gmail', case=False , na=False)]

Empty DataFrame
Columns: [Patient_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, Blood_Group, Marital_Status, Phone_Number, Email, Address, City, State, Country, Pincode, Height_cm, Weight_kg, BMI, Smoking_Status, Alcohol_Consumption, Chronic_Condition, Primary_Doctor_ID, Insurance_Provider, Insurance_Policy_No, Registration_Date]
Index: []

[0 rows x 25 columns]

32.	Find patients whose Patient_ID starts with “P1”

📝 Note: Prefix-based filtering.

In [159]:
df[df['Patient_ID'].str.contains('P1')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
9999,P10000,Vikas,Sharma,Male,53,1972-09-06,B+,Married,9422488565,user10000@mail.com,...,153,78,33.3,Yes,No,Asthma,D110,Star Health,POL199160,2022-12-31
10000,P10001,Anjali,Singh,Female,51,1974-04-11,A+,Single,9035400570,user10001@mail.com,...,168,82,29.1,Yes,Occasionally,Hypertension,D105,Reliance General,POL124664,2021-06-12
10001,P10002,Anjali,Singh,Female,56,1969-05-19,B+,Single,9248354863,user10002@mail.com,...,150,90,40.0,No,Occasionally,Thyroid,D101,Reliance General,POL280028,2020-12-29
10002,P10003,Amit,Kulkarni,Male,38,1987-07-10,A-,Single,9523763075,user10003@mail.com,...,173,60,20.0,No,Occasionally,Thyroid,D107,New India Assurance,POL954684,2020-01-05
10003,P10004,Pooja,Nair,Male,46,1979-07-20,AB+,Married,9702294516,user10004@mail.com,...,152,51,22.1,No,Occasionally,Asthma,D102,ICICI Lombard,POL788093,2021-06-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19994,P19995,Suresh,Singh,Male,58,1967-01-14,AB+,Married,9142595611,user19995@mail.com,...,156,77,31.6,Yes,No,Hypertension,D109,HDFC Ergo,POL281542,2021-12-02
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,173,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,174,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,167,55,19.7,No,Occasionally,NaN,D105,Star Health,POL129135,2020-03-02
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,157,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02

33.	Find patients with weight above average weight

📝 Note: First calculate average weight, then filter.

In [36]:
df.groupby('Gender')['Weight_kg'].mean()

Gender
Female    69.975147
Male      69.976336
Name: Weight_kg, dtype: float64

34.	Find patients having Asthma or Thyroid

📝 Note: OR condition on Chronic_Condition column.

In [160]:
df[(df['Chronic_Condition']=='Asthma') | (df['Chronic_Condition']=='Thyroid')]

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Height_cm,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,155,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,169,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25
8,P00009,Kavita,Mehta,Female,30,1995-03-30,A+,Married,9853397700,user9@mail.com,...,155,68,28.3,Yes,No,Asthma,D103,Star Health,POL233712,2020-10-24
11,P00012,Rahul,Mehta,Female,50,1975-11-26,AB-,Married,9380410557,user12@mail.com,...,170,82,28.4,No,Occasionally,Asthma,D110,Reliance General,POL684731,2022-12-15
14,P00015,Suresh,Gupta,Male,50,1975-10-23,B-,Single,9498079887,user15@mail.com,...,171,75,25.6,No,No,Thyroid,D106,HDFC Ergo,POL258655,2023-10-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19978,P19979,Kavita,Gupta,Male,42,1983-09-27,O+,Married,9514834444,user19979@mail.com,...,163,64,24.1,No,Occasionally,Thyroid,D109,Reliance General,POL399622,2020-03-14
19981,P19982,Vikas,Singh,Female,42,1983-10-27,O+,Single,9179699811,user19982@mail.com,...,164,61,22.7,No,No,Thyroid,D107,Reliance General,POL112807,2021-09-22
19990,P19991,Vikas,Joshi,Male,55,1970-05-20,O+,Single,9551275487,user19991@mail.com,...,160,70,27.3,Yes,No,Thyroid,D108,New India Assurance,POL934323,2020-05-26
19991,P19992,Vikas,Sharma,Female,39,1986-11-17,AB-,Single,9978783159,user19992@mail.com,...,159,85,33.6,Yes,Occasionally,Thyroid,D102,ICICI Lombard,POL329569,2023-12-03
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,155,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18

35.	Find patients whose BMI is below 18.5

📝 Note: BMI < 18.5 indicates underweight.

In [162]:
df['Under_weighted']=df['BMI']<18.5
df['Under_weighted']

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: Under_weighted, Length: 20000, dtype: bool

**SECTION 3: AGGREGATION & GROUPBY (36–55)**

36.	Find the average age of patients

📝 Note: Use mean aggregation on Age column.

In [163]:
df.groupby('Age')['Age'].mean()

Age
27    27.0
28    28.0
29    29.0
30    30.0
31    31.0
32    32.0
33    33.0
34    34.0
35    35.0
36    36.0
37    37.0
38    38.0
39    39.0
40    40.0
41    41.0
42    42.0
43    43.0
44    44.0
45    45.0
46    46.0
47    47.0
48    48.0
49    49.0
50    50.0
51    51.0
52    52.0
53    53.0
54    54.0
55    55.0
56    56.0
57    57.0
58    58.0
59    59.0
60    60.0
Name: Age, dtype: float64

37.	Find average BMI by gender

📝 Note: Group by Gender and calculate mean BMI.

In [164]:
df.groupby('Gender')['BMI'].mean()

Gender
Female    25.939014
Male      25.915914
Name: BMI, dtype: float64

38.	Count number of patients per city

📝 Note: Group by City and count rows.

In [165]:
df.groupby('City')['Patient_ID'].count()

City
Mumbai         3922
Nagpur         4042
Nashik         4032
Navi Mumbai    3905
Pune           4099
Name: Patient_ID, dtype: int64

39.	Count number of patients per chronic condition

📝 Note: Shows disease distribution.

In [166]:
df.groupby('Chronic_Condition')['Patient_ID'].count()

Chronic_Condition
Asthma          3998
Diabetes        4014
Hypertension    3965
Thyroid         4014
Name: Patient_ID, dtype: int64

40.	Find maximum age per city

📝 Note: Group by City and apply max on Age.

In [167]:
df.groupby('City')['Age'].max()

City
Mumbai         60
Nagpur         60
Nashik         60
Navi Mumbai    60
Pune           60
Name: Age, dtype: int64

41.	Find minimum BMI per gender
📝 Note: Identify lowest BMI per gender group.

In [168]:
df.groupby('Gender')['BMI'].min()

Gender
Female    15.4
Male      15.4
Name: BMI, dtype: float64

42.	Find average height per city

📝 Note: City-wise physical comparison.

In [169]:
df.groupby('City')['Height_cm'].mean()

City
Mumbai         164.782764
Nagpur         165.090549
Nashik         165.035218
Navi Mumbai    165.071191
Pune           165.030007
Name: Height_cm, dtype: float64

43.	Find total patients per insurance provider

📝 Note: Count patients under each insurer.

In [170]:
df.groupby('Insurance_Provider')['Patient_ID'].count()

Insurance_Provider
HDFC Ergo              3942
ICICI Lombard          3969
New India Assurance    4077
Reliance General       3976
Star Health            4036
Name: Patient_ID, dtype: int64

44.	Find city with highest number of patients

📝 Note: Sort aggregated counts.

In [48]:
df.groupby('City')['Patient_ID'].count().sort_values(ascending=False)

City
Pune           4099
Nagpur         4042
Nashik         4032
Mumbai         3922
Navi Mumbai    3905
Name: Patient_ID, dtype: int64

45.	Find average BMI per smoking status

📝 Note: Compare smokers vs non-smokers.

In [171]:
df.groupby('Smoking_Status')['BMI'].mean()

Smoking_Status
No     25.918135
Yes    25.936532
Name: BMI, dtype: float64

46.	Find number of patients per blood group

📝 Note: Useful for healthcare planning.

In [50]:
df.groupby('Blood_Group')['Patient_ID'].count()

Blood_Group
A+     2590
A-     2493
AB+    2565
AB-    2417
B+     2521
B-     2505
O+     2410
O-     2499
Name: Patient_ID, dtype: int64

47.	Find average age per marital status

📝 Note: Demographic insight.

In [51]:
df.groupby('Marital_Status')['Age'].mean()

Marital_Status
Married    43.895618
Single     43.869951
Name: Age, dtype: float64

48.	Find highest BMI per chronic condition

📝 Note: Identify extreme risk cases.

In [52]:
df.groupby('Chronic_Condition')['BMI'].max()

Chronic_Condition
Asthma          40.0
Diabetes        40.0
Hypertension    40.0
Thyroid         40.0
Name: BMI, dtype: float64

49.	Find lowest weight per city

📝 Note: Detect outliers.

In [53]:
df.groupby('City')['Weight_kg'].min()

City
Mumbai         50
Nagpur         50
Nashik         50
Navi Mumbai    50
Pune           50
Name: Weight_kg, dtype: int64

50.	Count patients registered per year

📝 Note: Extract year from Registration_Date.

In [173]:
df['Registration_Date'] = pd.to_datetime(df['Registration_Date'])

In [174]:
df['Registration_Date'].dt.year.value_counts().sort_index()

Registration_Date
2020    4944
2021    4811
2022    4837
2023    4838
2024     570
Name: count, dtype: int64

51.	Find insurance provider with maximum patients

📝 Note: Rank insurance providers.

In [55]:
df.groupby('Insurance_Provider')['Patient_ID'].count().sort_values(ascending=False)

Insurance_Provider
New India Assurance    4077
Star Health            4036
Reliance General       3976
ICICI Lombard          3969
HDFC Ergo              3942
Name: Patient_ID, dtype: int64

52.	Find number of patients per doctor

📝 Note: Doctor workload analysis

In [56]:
df.groupby('Primary_Doctor_ID')['Patient_ID'].count()

Primary_Doctor_ID
D100    1821
D101    1789
D102    1841
D103    1846
D104    1820
D105    1809
D106    1733
D107    1857
D108    1852
D109    1806
D110    1826
Name: Patient_ID, dtype: int64

53.	Find average BMI per doctor

📝 Note: Care quality insight

In [57]:
df.groupby('Primary_Doctor_ID')['BMI'].mean()

Primary_Doctor_ID
D100    25.969577
D101    25.832700
D102    26.107496
D103    26.128277
D104    25.819615
D105    25.869707
D106    25.856145
D107    25.877975
D108    26.002376
D109    25.864673
D110    25.860843
Name: BMI, dtype: float64

54.	Find total patients with chronic conditions

📝 Note: Exclude "None".

In [58]:
df.groupby('Chronic_Condition')['Patient_ID'].count()

Chronic_Condition
Asthma          3998
Diabetes        4014
Hypertension    3965
Thyroid         4014
Name: Patient_ID, dtype: int64

55.	Find percentage of smokers vs non-smokers

📝 Note: Convert counts into percentages.

In [59]:
smoker= df['Smoking_Status'].value_counts(normalize=True)* 100
smoker

Smoking_Status
No     50.18
Yes    49.82
Name: proportion, dtype: float64

**SECTION 4: DATA TRANSFORMATION (56–75)**

56.	Create a new column Age_Group (Young, Adult, Senior)

📝 Note:

o	Age 5–25 → Young

o	Age 26–50 → Adult

o	Age Above 50 → Senior

In [60]:
df['Age_Group']=df['Age'].apply(lambda i:'Young' if i>=5 and i<=25
                                       else ('Adult' if i>=26 and i<=50
                                       else 'Senior'))
df['Age_Group']

0         Adult
1         Adult
2        Senior
3         Adult
4         Adult
          ...
19995     Adult
19996    Senior
19997     Adult
19998     Adult
19999    Senior
Name: Age_Group, Length: 20000, dtype: object

57.	Create a column Risk_Level based on BMI

📝 Note:

o	BMI < 18.5 → Low

o	BMI 18.5–25 → Normal

o	BMI 25–30 → Medium

o	BMI > 30 → High

In [61]:
df['Risk_level']=df['BMI'].apply(lambda i:'Low' if i<18.5 else ('Normal' if i<=25 else ('Medium' if i<=30 else 'High')))
df['Risk_level']

0        Normal
1        Medium
2        Normal
3        Normal
4          High
          ...
19995    Normal
19996    Normal
19997    Normal
19998    Medium
19999      High
Name: Risk_level, Length: 20000, dtype: object

58.	Convert Registration_Date to datetime

📝 Note: Required before extracting year or month

In [62]:
df['Registration_Month']=pd.to_datetime(df['Registration_Date']).dt.month
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,Thyroid,D110,Reliance General,POL127128,2023-10-19,2023,False,Adult,Normal,10
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,NaN,D102,Star Health,POL919951,2023-02-12,2023,False,Adult,Medium,2
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,Thyroid,D109,New India Assurance,POL924889,2020-07-25,2020,False,Senior,Normal,7
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,Diabetes,D101,Reliance General,POL912134,2020-05-17,2020,False,Adult,Normal,5
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,Hypertension,D110,Reliance General,POL911663,2021-12-04,2021,False,Adult,High,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03,2021,False,Adult,Normal,7
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,Hypertension,D102,New India Assurance,POL513474,2024-01-18,2024,False,Senior,Normal,1
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,NaN,D105,Star Health,POL129135,2020-03-02,2020,False,Adult,Normal,3
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,NaN,D108,ICICI Lombard,POL531241,2023-04-02,2023,False,Adult,Medium,4
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,Asthma,D101,New India Assurance,POL666690,2020-02-18,2020,False,Senior,High,2

59.	Extract Registration Year

📝 Note: Create a new column storing year only

In [63]:
df['Registartion_Year']=pd.to_datetime(df['Registration_Date']).dt.year
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month,Registartion_Year
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,D110,Reliance General,POL127128,2023-10-19,2023,False,Adult,Normal,10,2023
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,D102,Star Health,POL919951,2023-02-12,2023,False,Adult,Medium,2,2023
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,D109,New India Assurance,POL924889,2020-07-25,2020,False,Senior,Normal,7,2020
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,D101,Reliance General,POL912134,2020-05-17,2020,False,Adult,Normal,5,2020
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,D110,Reliance General,POL911663,2021-12-04,2021,False,Adult,High,12,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,D108,ICICI Lombard,POL308290,2021-07-03,2021,False,Adult,Normal,7,2021
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,D102,New India Assurance,POL513474,2024-01-18,2024,False,Senior,Normal,1,2024
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,D105,Star Health,POL129135,2020-03-02,2020,False,Adult,Normal,3,2020
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,D108,ICICI Lombard,POL531241,2023-04-02,2023,False,Adult,Medium,4,2023
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,D101,New India Assurance,POL666690,2020-02-18,2020,False,Senior,High,2,2020

60.	Extract Registration Month

📝 Note: Month should be numeric (1–12).

In [64]:
df['Registration_Month']=pd.to_datetime(df['Registration_Date']).dt.month
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month,Registartion_Year
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,D110,Reliance General,POL127128,2023-10-19,2023,False,Adult,Normal,10,2023
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,D102,Star Health,POL919951,2023-02-12,2023,False,Adult,Medium,2,2023
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,D109,New India Assurance,POL924889,2020-07-25,2020,False,Senior,Normal,7,2020
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,D101,Reliance General,POL912134,2020-05-17,2020,False,Adult,Normal,5,2020
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,D110,Reliance General,POL911663,2021-12-04,2021,False,Adult,High,12,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,D108,ICICI Lombard,POL308290,2021-07-03,2021,False,Adult,Normal,7,2021
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,D102,New India Assurance,POL513474,2024-01-18,2024,False,Senior,Normal,1,2024
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,D105,Star Health,POL129135,2020-03-02,2020,False,Adult,Normal,3,2020
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,D108,ICICI Lombard,POL531241,2023-04-02,2023,False,Adult,Medium,4,2023
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,D101,New India Assurance,POL666690,2020-02-18,2020,False,Senior,High,2,2020

61.	Create column Is_Senior (Age > 60)

📝 Note: True if Age > 60, else False.

In [65]:
df['Is_Senior']=df['Age'].apply(lambda i: 'Senior'if i>60  else'Not Senior')
df['Is_Senior']

0        Not Senior
1        Not Senior
2        Not Senior
3        Not Senior
4        Not Senior
            ...
19995    Not Senior
19996    Not Senior
19997    Not Senior
19998    Not Senior
19999    Not Senior
Name: Is_Senior, Length: 20000, dtype: object

62.	Create column High_Risk_Patient

📝 Note:

o	BMI > 30

o	AND Chronic_Condition ≠ "None"

In [66]:
df['High_Risk_Patient']=(df['BMI']>30) & (df['Chronic_Condition']!="None")
df['High_Risk_Patient']

0        False
1        False
2        False
3        False
4         True
         ...
19995    False
19996    False
19997    False
19998    False
19999     True
Name: High_Risk_Patient, Length: 20000, dtype: bool

63.	Convert Gender column to category type

📝 Note: Improves memory efficiency.

In [67]:
df['Gender'] = df['Gender'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             20000 non-null  object
 1   First_Name             20000 non-null  object
 2   Last_Name              20000 non-null  object
 3   Gender                 20000 non-null  category
 4   Age                    20000 non-null  int64
 5   Date_of_Birth          20000 non-null  object
 6   Blood_Group            20000 non-null  object
 7   Marital_Status         20000 non-null  object
 8   Phone_Number           20000 non-null  int64
 9   Email                  20000 non-null  object
 10  Address                20000 non-null  object
 11  City                   20000 non-null  object
 12  State                  20000 non-null  object
 13  Country                20000 non-null  object
 14  Pincode                20000 non-null  int64
 15  Height_cm              20000 non-null  int64
 16  Weight_kg              20000 non-null  int64
 17  BMI                    20000 non-null  float64
 18  Smoking_Status         20000 non-null  object
 19  Alcohol_Consumption    20000 non-null  object
 20  Chronic_Condition      15991 non-null  object
 21  Primary_Doctor_ID      20000 non-null  object
 22  Insurance_Provider     20000 non-null  object
 23  Insurance_Policy_No    20000 non-null  object
 24  Registration_Date      20000 non-null  object
 25  Registration_Date_new  20000 non-null  int32
 26  Under_weighted         20000 non-null  bool
 27  Age_Group              20000 non-null  object
 28  Risk_level             20000 non-null  object
 29  Registration_Month     20000 non-null  int32
 30  Registartion_Year      20000 non-null  int32
 31  Is_Senior              20000 non-null  object
 32  High_Risk_Patient      20000 non-null  bool
dtypes: bool(2), category(1), float64(1), int32(3), int64(5), object(21)
memory usage: 4.4+ MB

64.	Convert Blood_Group column to category

📝 Note: Limited unique values → ideal for category

In [68]:
df['Blood_Group']=df['Blood_Group'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             20000 non-null  object
 1   First_Name             20000 non-null  object
 2   Last_Name              20000 non-null  object
 3   Gender                 20000 non-null  category
 4   Age                    20000 non-null  int64
 5   Date_of_Birth          20000 non-null  object
 6   Blood_Group            20000 non-null  category
 7   Marital_Status         20000 non-null  object
 8   Phone_Number           20000 non-null  int64
 9   Email                  20000 non-null  object
 10  Address                20000 non-null  object
 11  City                   20000 non-null  object
 12  State                  20000 non-null  object
 13  Country                20000 non-null  object
 14  Pincode                20000 non-null  int64
 15  Height_cm              20000 non-null  int64
 16  Weight_kg              20000 non-null  int64
 17  BMI                    20000 non-null  float64
 18  Smoking_Status         20000 non-null  object
 19  Alcohol_Consumption    20000 non-null  object
 20  Chronic_Condition      15991 non-null  object
 21  Primary_Doctor_ID      20000 non-null  object
 22  Insurance_Provider     20000 non-null  object
 23  Insurance_Policy_No    20000 non-null  object
 24  Registration_Date      20000 non-null  object
 25  Registration_Date_new  20000 non-null  int32
 26  Under_weighted         20000 non-null  bool
 27  Age_Group              20000 non-null  object
 28  Risk_level             20000 non-null  object
 29  Registration_Month     20000 non-null  int32
 30  Registartion_Year      20000 non-null  int32
 31  Is_Senior              20000 non-null  object
 32  High_Risk_Patient      20000 non-null  bool
dtypes: bool(2), category(2), float64(1), int32(3), int64(5), object(20)
memory usage: 4.3+ MB

65.	Rename column Phone_Number to Contact_Number

📝 Note: Use rename operation.

In [69]:
df=df.rename(columns={'Phone_Number':'Contact_Number'})
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Email,...,Insurance_Policy_No,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month,Registartion_Year,Is_Senior,High_Risk_Patient
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,POL127128,2023-10-19,2023,False,Adult,Normal,10,2023,Not Senior,False
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,POL919951,2023-02-12,2023,False,Adult,Medium,2,2023,Not Senior,False
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,POL924889,2020-07-25,2020,False,Senior,Normal,7,2020,Not Senior,False
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,POL912134,2020-05-17,2020,False,Adult,Normal,5,2020,Not Senior,False
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,POL911663,2021-12-04,2021,False,Adult,High,12,2021,Not Senior,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,POL308290,2021-07-03,2021,False,Adult,Normal,7,2021,Not Senior,False
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,POL513474,2024-01-18,2024,False,Senior,Normal,1,2024,Not Senior,False
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,POL129135,2020-03-02,2020,False,Adult,Normal,3,2020,Not Senior,False
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,POL531241,2023-04-02,2023,False,Adult,Medium,4,2023,Not Senior,False
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,POL666690,2020-02-18,2020,False,Senior,High,2,2020,Not Senior,True

66.	Drop Email column

📝 Note: Remove unnecessary or sensitive data

In [70]:
df = df.drop(columns=['Email'])

In [71]:
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,Insurance_Policy_No,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month,Registartion_Year,Is_Senior,High_Risk_Patient
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,Local Address,...,POL127128,2023-10-19,2023,False,Adult,Normal,10,2023,Not Senior,False
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,POL919951,2023-02-12,2023,False,Adult,Medium,2,2023,Not Senior,False
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,Local Address,...,POL924889,2020-07-25,2020,False,Senior,Normal,7,2020,Not Senior,False
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,Local Address,...,POL912134,2020-05-17,2020,False,Adult,Normal,5,2020,Not Senior,False
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,Local Address,...,POL911663,2021-12-04,2021,False,Adult,High,12,2021,Not Senior,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,Local Address,...,POL308290,2021-07-03,2021,False,Adult,Normal,7,2021,Not Senior,False
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,Local Address,...,POL513474,2024-01-18,2024,False,Senior,Normal,1,2024,Not Senior,False
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,Local Address,...,POL129135,2020-03-02,2020,False,Adult,Normal,3,2020,Not Senior,False
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,Local Address,...,POL531241,2023-04-02,2023,False,Adult,Medium,4,2023,Not Senior,False
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,Local Address,...,POL666690,2020-02-18,2020,False,Senior,High,2,2020,Not Senior,True

67.	Fill missing Chronic_Condition with “Unknown”

📝 Note: Handle missing values.

In [72]:
df['Chronic_Condition'].fillna('Unknown',inplace=True)
df['Chronic_Condition']

/tmp/ipykernel_45094/3979773431.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Chronic_Condition'].fillna('Unknown',inplace=True)

0             Thyroid
1             Unknown
2             Thyroid
3            Diabetes
4        Hypertension
             ...
19995    Hypertension
19996    Hypertension
19997         Unknown
19998         Unknown
19999          Asthma
Name: Chronic_Condition, Length: 20000, dtype: object

68.	Create BMI_Category

📝 Note:

o	<18.5 → Underweight

o	18.5–25 → Normal

o	25–30 → Overweight

o	30 → Obese

In [73]:
df['BMI_Category']=df['BMI'].apply(lambda i: 'Underweight'if i<18.5 else('Normal'if 18.5<=i<25 else('Overweight' if 25<=i<30 else'Obese')))
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,Registration_Date,Registration_Date_new,Under_weighted,Age_Group,Risk_level,Registration_Month,Registartion_Year,Is_Senior,High_Risk_Patient,BMI_Category
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,Local Address,...,2023-10-19,2023,False,Adult,Normal,10,2023,Not Senior,False,Normal
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,Local Address,...,2023-02-12,2023,False,Adult,Medium,2,2023,Not Senior,False,Overweight
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,Local Address,...,2020-07-25,2020,False,Senior,Normal,7,2020,Not Senior,False,Normal
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,Local Address,...,2020-05-17,2020,False,Adult,Normal,5,2020,Not Senior,False,Normal
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,Local Address,...,2021-12-04,2021,False,Adult,High,12,2021,Not Senior,True,Obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,Local Address,...,2021-07-03,2021,False,Adult,Normal,7,2021,Not Senior,False,Normal
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,Local Address,...,2024-01-18,2024,False,Senior,Normal,1,2024,Not Senior,False,Normal
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,Local Address,...,2020-03-02,2020,False,Adult,Normal,3,2020,Not Senior,False,Normal
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,Local Address,...,2023-04-02,2023,False,Adult,Medium,4,2023,Not Senior,False,Overweight
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,Local Address,...,2020-02-18,2020,False,Senior,High,2,2020,Not Senior,True,Obese

69.	Normalize Height column

📝 Note: Scale values between 0 and 1.

In [74]:
df['Height_Normalized'] = (df['Height_cm'] - df['Height_cm'].min()) / (df['Height_cm'].max() - df['Height_cm'].min())
df['Height_Normalized']

0        0.166667
1        0.600000
2        0.633333
3        0.400000
4        0.033333
           ...
19995    0.766667
19996    0.800000
19997    0.566667
19998    0.233333
19999    0.166667
Name: Height_Normalized, Length: 20000, dtype: float64

70.	Standardize Weight column

📝 Note: Mean = 0, Standard Deviation = 1.

In [75]:
df['Weight_Standardized'] = (df['Weight_kg'] - df['Weight_kg'].mean()) / df['Weight_kg'].std()
df['Weight_Standardized']

0       -1.688900
1        0.340240
2        0.086598
3       -0.843425
4        1.439358
           ...
19995   -0.589782
19996   -0.758877
19997   -1.266162
19998    0.086598
19999    1.608453
Name: Weight_Standardized, Length: 20000, dtype: float64

71.	Add column Insurance_Status (Yes/No)

📝 Note: Yes if Insurance_Provider exists, else No

In [76]:
df['Insurance_Status']=np.where(df['Insurance_Provider'],'Yes','No')

In [77]:
df['Insurance_Status']

0        Yes
1        Yes
2        Yes
3        Yes
4        Yes
        ...
19995    Yes
19996    Yes
19997    Yes
19998    Yes
19999    Yes
Name: Insurance_Status, Length: 20000, dtype: object

72.	Create column Patient_Location

📝 Note: Combine City and State with separator.

In [78]:
df['Patient_Location'] = df['City'] + ", " + df['State']

In [79]:
df['Patient_Location']

0        Navi Mumbai, Maharashtra
1             Mumbai, Maharashtra
2             Nashik, Maharashtra
3             Mumbai, Maharashtra
4        Navi Mumbai, Maharashtra
                   ...
19995    Navi Mumbai, Maharashtra
19996    Navi Mumbai, Maharashtra
19997         Nagpur, Maharashtra
19998         Nagpur, Maharashtra
19999         Nagpur, Maharashtra
Name: Patient_Location, Length: 20000, dtype: object

73.	Sort patients by BMI descending

📝 Note: Highest BMI first.

In [80]:
df['BMI'].sort_values(ascending=False)

17826    40.0
10001    40.0
10369    40.0
7256     40.0
1953     40.0
         ...
10472    15.4
9592     15.4
19194    15.4
15514    15.4
19909    15.4
Name: BMI, Length: 20000, dtype: float64

74.	Reset index after sorting

📝 Note: Clean index after rearranging rows

In [176]:
df.reset_index(drop=True,inplace=True)
df

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Phone_Number,Email,...,Weight_kg,BMI,Smoking_Status,Alcohol_Consumption,Chronic_Condition,Primary_Doctor_ID,Insurance_Provider,Insurance_Policy_No,Registration_Date,Under_weighted
0,P00001,Suresh,Iyer,Male,38,1987-11-23,B+,Single,9698790602,user1@mail.com,...,50,20.8,Yes,Occasionally,Thyroid,D110,Reliance General,POL127128,2023-10-19,False
1,P00002,Amit,Sharma,Female,38,1987-04-28,B+,Married,9762620912,user2@mail.com,...,74,26.2,Yes,Occasionally,NaN,D102,Star Health,POL919951,2023-02-12,False
2,P00003,Neha,Joshi,Male,56,1969-12-29,AB-,Single,9522528550,user3@mail.com,...,71,24.9,No,No,Thyroid,D109,New India Assurance,POL924889,2020-07-25,False
3,P00004,Anjali,Patil,Male,47,1978-12-04,A-,Married,9196136323,user4@mail.com,...,60,22.9,No,No,Diabetes,D101,Reliance General,POL912134,2020-05-17,False
4,P00005,Rohan,Verma,Male,41,1984-02-11,A-,Single,9644918514,user5@mail.com,...,87,38.2,No,No,Hypertension,D110,Reliance General,POL911663,2021-12-04,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,P19996,Anjali,Mehta,Male,36,1989-10-07,A-,Single,9990287038,user19996@mail.com,...,63,21.0,No,Occasionally,Hypertension,D108,ICICI Lombard,POL308290,2021-07-03,False
19996,P19997,Vikas,Verma,Female,57,1968-10-05,AB-,Single,9498150434,user19997@mail.com,...,61,20.1,Yes,Occasionally,Hypertension,D102,New India Assurance,POL513474,2024-01-18,False
19997,P19998,Anjali,Singh,Female,46,1979-01-16,A-,Married,9852974113,user19998@mail.com,...,55,19.7,No,Occasionally,NaN,D105,Star Health,POL129135,2020-03-02,False
19998,P19999,Amit,Sharma,Female,43,1982-07-30,A-,Single,9925330649,user19999@mail.com,...,71,28.8,Yes,Occasionally,NaN,D108,ICICI Lombard,POL531241,2023-04-02,False
19999,P20000,Pooja,Gupta,Female,58,1967-02-17,O-,Single,9951983597,user20000@mail.com,...,89,37.0,Yes,Occasionally,Asthma,D101,New India Assurance,POL666690,2020-02-18,False

75.	Select top 10 highest BMI patients

📝 Note: Used for high-risk analysis

In [82]:
df.sort_values(by='BMI', ascending=False).head(10)

,Patient_ID,First_Name,Last_Name,Gender,Age,Date_of_Birth,Blood_Group,Marital_Status,Contact_Number,Address,...,Risk_level,Registration_Month,Registartion_Year,Is_Senior,High_Risk_Patient,BMI_Category,Height_Normalized,Weight_Standardized,Insurance_Status,Patient_Location
17826,P17827,Kavita,Sharma,Female,40,1985-08-05,AB+,Single,9425136045,Local Address,...,High,4,2022,Not Senior,True,Obese,0.0,1.693001,Yes,"Pune, Maharashtra"
10001,P10002,Anjali,Singh,Female,56,1969-05-19,B+,Single,9248354863,Local Address,...,High,12,2020,Not Senior,True,Obese,0.0,1.693001,Yes,"Nagpur, Maharashtra"
10369,P10370,Pooja,Singh,Male,34,1991-10-01,O-,Single,9637966832,Local Address,...,High,10,2020,Not Senior,True,Obese,0.0,1.693001,Yes,"Pune, Maharashtra"
7256,P07257,Vikas,Iyer,Male,38,1987-02-22,B+,Married,9754719239,Local Address,...,High,3,2021,Not Senior,True,Obese,0.0,1.693001,Yes,"Navi Mumbai, Maharashtra"
1953,P01954,Pooja,Patil,Male,54,1971-07-26,B+,Single,9195154533,Local Address,...,High,3,2023,Not Senior,True,Obese,0.0,1.693001,Yes,"Nashik, Maharashtra"
2913,P02914,Rahul,Joshi,Female,55,1970-06-27,O+,Married,9669114317,Local Address,...,High,5,2021,Not Senior,True,Obese,0.0,1.693001,Yes,"Navi Mumbai, Maharashtra"
14250,P14251,Rohan,Patil,Female,40,1985-06-23,AB-,Single,9713111126,Local Address,...,High,10,2023,Not Senior,True,Obese,0.0,1.693001,Yes,"Navi Mumbai, Maharashtra"
14268,P14269,Rahul,Singh,Male,35,1990-07-22,A-,Single,9872545141,Local Address,...,High,3,2023,Not Senior,True,Obese,0.0,1.693001,Yes,"Nagpur, Maharashtra"
5024,P05025,Anjali,Iyer,Female,57,1968-11-13,O-,Single,9737178788,Local Address,...,High,5,2021,Not Senior,True,Obese,0.0,1.693001,Yes,"Nagpur, Maharashtra"
17251,P17252,Anjali,Joshi,Female,48,1977-10-07,O-,Married,9254411475,Local Address,...,High,5,2020,Not Senior,True,Obese,0.0,1.693001,Yes,"Pune, Maharashtra"

**SECTION 5: ADVANCED / ANALYTICAL QUESTIONS (76–90)**

76.	Find top 5 cities with highest average BMI

📝 Note: Group → Mean → Sort → Top 5.

In [83]:
df.groupby('City')['BMI'].mean().sort_values(ascending=False).head()

City
Mumbai         25.984345
Pune           25.945328
Nashik         25.922247
Navi Mumbai    25.911626
Nagpur         25.873850
Name: BMI, dtype: float64

77.	Find bottom 5 cities with lowest average BMI

📝 Note: Ascending order.

In [84]:
df.groupby('City')['BMI'].mean().sort_values().head()

City
Nagpur         25.873850
Navi Mumbai    25.911626
Nashik         25.922247
Pune           25.945328
Mumbai         25.984345
Name: BMI, dtype: float64

78.	Find patients at high cardiovascular risk

📝 Note:

o	Age > 50

o	BMI > 30

o	Chronic condition present

In [85]:
df['high_cardiovascular_risk']=(df['Chronic_Condition']=='present') & (df['Age']>50) & (df['BMI']>30)

In [86]:
df['high_cardiovascular_risk']

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: high_cardiovascular_risk, Length: 20000, dtype: bool

79.	Find doctor handling maximum chronic patients

📝 Note: Filter chronic patients, then group by doctor.

In [87]:
a = df[df['Chronic_Condition'] != 'Unknown']
top_doctor = a.groupby('Primary_Doctor_ID')['Patient_ID'].count().sort_values(ascending=False)
print(top_doctor.head(1))

Primary_Doctor_ID
D107    1493
Name: Patient_ID, dtype: int64

80.	Find insurance provider covering most senior citizens

📝 Note: Senior = Age > 60.

In [88]:
seniors_df = df[df['Age'] > 60]
top_provider = seniors_df['Insurance_Provider'].max()
print(top_provider)

nan

81.	Find patients eligible for lifestyle counseling

📝 Note: BMI > 25 OR Smoking = Yes OR Alcohol = Occasionally

In [89]:
df['lifestyle_counseling']=(df['BMI']>25) | (df['Smoking_Status']=='Yes') | (df['Alcohol_Consumption']=='Occasionally')
df['lifestyle_counseling']

0         True
1         True
2        False
3        False
4         True
         ...
19995     True
19996     True
19997     True
19998     True
19999     True
Name: lifestyle_counseling, Length: 20000, dtype: bool

82.	Identify potential ICU-risk patients

📝 Note: Age > 65 AND BMI > 30 AND chronic condition present.

In [90]:
df['ICU-risk']=(df['Age']>30) & (df['Chronic_Condition']=='Yes')

In [91]:
df['ICU-risk']

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Name: ICU-risk, Length: 20000, dtype: bool

83.	Find correlation between Age and BMI

📝 Note: Measures relationship strength.

In [92]:
correlation = df['Age'].corr(df['BMI'])
print(f"Correlation between Age and BMI: {correlation:.2f}")

Correlation between Age and BMI: -0.01

84.	Detect BMI outliers using IQR

📝 Note:

o	Lower bound = Q1 − 1.5×IQR

o	Upper bound = Q3 + 1.5×IQR

In [104]:
Q1=df['BMI'].quantile(0.25)
Q3=df['BMI'].quantile(0.75)
IQR=Q3-Q1
Lower_bound=Q1-1.5*IQR
Upper_bound=Q3+1.5*IQR
Outliner=df[(df['BMI']<Lower_bound) | (df['BMI']>Upper_bound)]
print(f"Lower Bound: {Lower_bound}, Upper Bound: {Upper_bound}")
print(Outliner)

Lower Bound: 10.250000000000002, Upper Bound: 41.05
Empty DataFrame
Columns: [Patient_ID, First_Name, Last_Name, Gender, Age, Date_of_Birth, Blood_Group, Marital_Status, Contact_Number, Address, City, State, Country, Pincode, Height_cm, Weight_kg, BMI, Smoking_Status, Alcohol_Consumption, Chronic_Condition, Primary_Doctor_ID, Insurance_Provider, Insurance_Policy_No, Registration_Date, Registration_Date_new, Under_weighted, Age_Group, Risk_level, Registration_Month, Registartion_Year, Is_Senior, High_Risk_Patient, BMI_Category, Height_Normalized, Weight_Standardized, Insurance_Status, Patient_Location, high_cardiovascular_risk, lifestyle_counseling, ICU-risk]
Index: []

[0 rows x 40 columns]

85.	Create pivot table of Gender vs Chronic Condition

📝 Note: Rows = Gender, Columns = Chronic_Condition.

In [117]:
pivot_table=df.pivot_table(index='Gender', values='Chronic_Condition',aggfunc='count')
print(pivot_table)

        Chronic_Condition
Gender
Female               9858
Male                10142

/tmp/ipykernel_45094/2742968215.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot_table=df.pivot_table(index='Gender', values='Chronic_Condition',aggfunc='count')

86.	Create pivot of City vs Smoking_Status

📝 Note: Cross-tab city and smoking habits.

In [119]:
pivot_table2=df.pivot_table(index='City',values='Smoking_Status',aggfunc='count')
print(pivot_table2)

             Smoking_Status
City
Mumbai                 3922
Nagpur                 4042
Nashik                 4032
Navi Mumbai            3905
Pune                   4099

87.	Calculate rolling average BMI by age

📝 Note: Use window size (e.g., 5).

In [123]:
age_bmi = df[['Age', 'BMI']]
age_bmi = age_bmi.sort_values('Age')
age_bmi['Rolling_Avg_BMI'] = age_bmi['BMI'].rolling(window=5, min_periods=1).mean()
print(age_bmi.head())

       Age   BMI  Rolling_Avg_BMI
12278   27  23.7        23.700000
846     27  25.1        24.400000
17446   27  32.4        27.066667
755     27  22.1        25.825000
760     27  30.5        26.760000

88.	Rank patients by BMI within each city

📝 Note: Ranking should reset per city.

In [126]:
df['BMI_Rank_In_City'] = df.groupby('City')['BMI'].rank(ascending=False, method='min')
df_sorted = df.sort_values(['City', 'BMI_Rank_In_City'])
df['BMI_Rank_In_City']

0        3186.0
1        1793.0
2        2193.0
3        2659.0
4          32.0
          ...
19995    3128.0
19996    3328.0
19997    3520.0
19998    1145.0
19999      90.0
Name: BMI_Rank_In_City, Length: 20000, dtype: float64

89.	Find percentile rank of BMI

📝 Note: Shows relative BMI position.

In [128]:
df['BMI_Percentile'] = df['BMI'].rank(pct=True) * 100
df_sorted = df.sort_values('BMI_Percentile', ascending=False)
df['BMI_Percentile']

0        18.4125
1        53.8275
2        45.2000
3        32.1975
4        99.0525
          ...
19995    19.5950
19996    14.4375
19997    12.3325
19998    70.8675
19999    97.7850
Name: BMI_Percentile, Length: 20000, dtype: float64

90.	Export cleaned DataFrame to CSV

📝 Note: Final output after transformations.

In [130]:
df.to_csv('cleaned_patient_data.csv', index=False)
print("File saved successfully!")

File saved successfully!